"""
YouTube 채널 영상 데이터를 가져와 data.js를 업데이트하는 스크립트.
GitHub Actions에서 YOUTUBE_API_KEY 환경변수를 통해 실행됩니다.
"""
import os
import json
import re
from datetime import datetime, timezone
from googleapiclient.discovery import build

# ── 설정 ────────────────────────────────────────────────────────────
API_KEY        = os.environ["YOUTUBE_API_KEY"]
CHANNEL_ID     = "UChnVG_s2dxy6Dmp7AOLdbLQ"
UPLOADS_PL_ID  = "UU" + CHANNEL_ID[2:]   # UC… → UU…
MAX_RESULTS    = 50
OUTPUT_FILE    = "data.js"
# ────────────────────────────────────────────────────────────────────


def best_thumbnail(thumbnails: dict) -> str:
    for key in ("maxres", "standard", "high", "medium", "default"):
        if key in thumbnails:
            return thumbnails[key]["url"]
    return ""


def fetch_all_videos(youtube) -> list[dict]:
    videos = []
    page_token = None

    while True:
        resp = youtube.playlistItems().list(
            part="snippet",
            playlistId=UPLOADS_PL_ID,
            maxResults=MAX_RESULTS,
            pageToken=page_token,
        ).execute()

        for item in resp.get("items", []):
            s = item["snippet"]
            videos.append({
                "title":       s["title"],
                "videoId":     s["resourceId"]["videoId"],
                "publishedAt": s["publishedAt"],
                "thumbnail":   best_thumbnail(s.get("thumbnails", {})),
                "description": s.get("description", "")[:200],
            })

        page_token = resp.get("nextPageToken")
        if not page_token:
            break

    return videos


def to_data_js(videos: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    json_str = json.dumps(videos, ensure_ascii=False, indent=4)
    return (
        f"// Auto-generated by GitHub Actions — do not edit manually\n"
        f"// Last updated: {now} | Total: {len(videos)} videos\n"
        f"window.VIDEOS_DATA = {json_str};\n"
    )


def main():
    youtube = build("youtube", "v3", developerKey=API_KEY)
    print(f"Fetching videos from playlist: {UPLOADS_PL_ID}")

    videos = fetch_all_videos(youtube)
    print(f"Fetched {len(videos)} videos")

    # Read existing data.js to check if anything changed
    existing_ids = set()
    if os.path.exists(OUTPUT_FILE):
        content = open(OUTPUT_FILE, encoding="utf-8").read()
        existing_ids = set(re.findall(r'"videoId":\s*"([^"]+)"', content))

    new_ids = {v["videoId"] for v in videos}
    added = new_ids - existing_ids
    if added:
        print(f"New videos detected ({len(added)}): {', '.join(added)}")
    else:
        print("No new videos since last run.")

    # Always write (updatedAt timestamp changes)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(to_data_js(videos))

    print(f"Written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
